name: Publish Package to Verdaccio [https://packages.cavrn.us/] on Commit

on:
  push:
    branches:
      - release
    tags:
      - '*' # Trigger on all tags
  workflow_dispatch:

jobs:
  publish:
    name: Publish to Verdaccio
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Delete .github folder
        run: rm -rf .github
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Verdaccio
        run: echo "//packages.cavrn.us/:_authToken=${{secrets.VERDACCIO_TOKEN}}" > ~/.npmrc

      - name: Publish to Verdaccio
        run: npm publish --registry https://packages.cavrn.us/
