name: Publish Package to Verdaccio on Commit

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Verdaccio
        run: echo "//packages.cavrn.us/:_authToken=${{secrets.VERDACCIO_TOKEN}}" > ~/.npmrc

      - name: Publish to Verdaccio
        run: npm publish --registry https://packages.cavrn.us/
