name: Publish Package to Verdaccio [https://packages.cavrn.us/] on Commit

on:
  release: # This should only happen when pushing a release ie. pushing tag.
    tags:
      - '*' # Trigger on all tags

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/') && github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
      - name: Delete .github folder
        run: rm -rf .github
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Verdaccio
        run: echo "//packages.cavrn.us/:_authToken=${{secrets.VERDACCIO_TOKEN}}" > ~/.npmrc

      - name: Publish to Verdaccio
        run: npm publish --registry https://packages.cavrn.us/
